### ISSUE TITLE
Dataset size does not match what is reported in the paper

### ISSUE THREAD

**Issue by dniku** [skywalker023/fantom#4]
According to the paper (page 5, "statistics"), dataset size should be:

* 1415 BELIEFQ[DIST.]s and BELIEFQ[CHOICE]s
* 703 FACTQs, ANSWERABILITY Q[LIST]s, and INFOACCESS Q[LIST]s, respectively
* 2689 ANSWERABILITY Q[Y/N]s and INFOACCESS Q[Y/N]s

The actual size is:

```python
!wget https://storage.googleapis.com/ai2-mosaic-public/projects/fantom/fantom.tar.gz
!tar xvf fantom.tar.gz

import json
import pandas as pd

with open('fantom_v1.json', 'r') as fp:
  fantom_data = json.load(fp)

df = pd.DataFrame(fantom_data)

template_str = 'Num of {metric}: {num}\n'
print(''.join([template_str.format(metric=el, num=sum(df[el].map(len))) for el in ('beliefQAs', 'infoAccessibilityQAs_binary', 'answerabilityQAs_binary')] +
              [template_str.format(metric=el, num=len(df[el])) for el in ('factQA', 'infoAccessibilityQA_list', 'answerabilityQA_list')])
)
```

```
Num of beliefQAs: 1540
Num of infoAccessibilityQAs_binary: 3571
Num of answerabilityQAs_binary: 3571
Num of factQA: 870
Num of infoAccessibilityQA_list: 870
Num of answerabilityQA_list: 870
```

So the difference is:

* `factQA`, `infoAccessibilityQA_list`, and `answerabilityQA_list`: 703 (paper) vs 870 (released)
* `beliefQAs`: 1415 (paper) vs 1540 (released)
* `infoAccessibilityQAs_binary` and `answerabilityQAs_binary`: 2689 (paper) vs 3571 (released)

**Comment by skywalker023** [comment]
Thanks for your interest in our work!
Yes, we have updated more questions for the public release after the camera ready submission.
